pipeline {
    agent any
    environment {
        AWS_REGION = "ap-northeast-2"
        REPO = "https://github.com/lsh5224/Terraform_test.git"
    }
    stages {
        stage('Clone Repo') {
            steps {
                sh 'git clone $REPO'
            }
        }
        stage('Fetch ECR Tags') {
            steps {
                script {
                    def repos = ["frontend", "backend-user", "backend-boards"]
                    def latestTags = [:]
                    for (repo in repos) {
                        def tags = sh(script: "aws ecr list-images --repository-name ${repo} --query 'imageIds[*].imageTag' --output text", returnStdout: true).trim().split()
                        latestTags[repo] = tags.sort().last()
                    }
                    writeFile file: 'Terraform_test/values.yaml', text: updateYamlWithTags(latestTags)
                }
            }
        }
        stage('Git Push') {
            steps {
                dir('Terraform_test') {
                    sh '''
                    git config --global user.email "jenkins@ci"
                    git config --global user.name "Jenkins CI"
                    git add .
                    git commit -m "Update image tags"
                    git push origin main
                    '''
                }
            }
        }
    }
}

def updateYamlWithTags(tags) {
    return """
backend:
  boards:
    tag: "${tags["backend-boards"]}"
  user:
    tag: "${tags["backend-user"]}"

frontend:
  tag: "${tags["frontend"]}"
"""
}
